title: David Bindel
email: bindel@cornell.edu
description: CS 5220 home page
baseurl: "/courses/CS5220/2020fa/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
